const works = [
  {
    id: 1,
    title: "Landscapes of Eorzea",
    image: "/art/eorzea1.jpg",
    category: ["paintings", "all"],
    url: "/landscapes_of_eorzea",
    imageFolder: "art/Landscapes_Of_Eorzea",
    images: [
      "landscape1.jpg",
      "landscape2.jpg",
      "landscape3.jpg",
      "landscape4.jpg",
    ],
  },
  {
    id: 2,
    title: "Tor(e)ment - BFA Thesis Exhibition",
    image: "/art/thesis1.jpg",
    category: ["mixed", "all"],
    url: "/thesis",
    imageFolder: "art/Thesis",
    images: [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
      "10.jpg",
      "11.jpg",
      "12.jpg",
      "13.jpg",
      "14.jpg",
      "15.jpg",
      "16.jpg",
      "17.jpg",
      "18.jpg",
      "19.jpg",
      "20.jpg",
      "23.jpg",
      "24.jpg",
      "25.jpg",
      "26.jpg",
    ],
  },
  {
    id: 3,
    title: "Portrait Paintings",
    image: "/art/portraitpainting1.jpg",
    category: ["paintings", "all"],
    url: "/portrait_paintings",
    imageFolder: "art/Portrait_Paintings",
    images: [
      "portraitpainting1.jpg",
      "portraitpainting2.jpg",
      "portraitpainting3.jpg",
      "portraitpainting4.jpg",
      "portraitpainting5.jpg",
      "portraitpainting6.jpg",
      "portraitpainting7.jpg",
      "portraitpainting8.jpg",
      "portraitpainting9.jpg",
      "portraitpainting10.jpg",
    ],
  },
  {
    id: 4,
    title: "Nature Paintings",
    image: "/art/naturepainting1.jpg",
    category: ["paintings", "all"],
    url: "/nature_paintings",
    imageFolder: "art/Nature_Paintings",
    images: [
      "naturepainting1.jpg",
      "naturepainting2.jpg",
      "naturepainting3.jpg",
      "naturepainting4.jpg",
      "naturepainting5.jpg",
      "naturepainting6.jpg",
    ],
  },
  {
    id: 5,
    title: "Misc. Photography",
    image: "/art/miscphoto1.jpg",
    category: ["photography", "all"],
    url: "/misc_photography",
    imageFolder: "art/Misc_Photography",
    images: [
      "miscphoto1.jpg",
      "miscphoto2.jpg",
      "miscphoto3.jpg",
      "miscphoto4.jpg",
      "miscphoto5.jpg",
    ],
  },
  {
    id: 6,
    title: "Digital Paintings",
    image: "/art/digitalpainting1.jpg",
    category: ["paintings", "all"],
    url: "/digital_paintings",
    imageFolder: "art/Digital_Paintings",
    images: ["digitalpainting1.jpg", "digitalpainting2.jpg"],
  },
  {
    id: 7,
    title: "Nature Photography",
    image: "/art/naturephoto1.jpg",
    category: ["photography", "all"],
    url: "/nature_photography",
    imageFolder: "art/Nature_Photography",
    images: [
      "naturephoto1.jpg",
      "naturephoto2.jpg",
      "naturephoto3.jpg",
      "naturephoto4.jpg",
      "naturephoto5.jpg",
      "naturephoto6.jpg",
      "naturephoto7.jpg",
      "naturephoto8.jpg",
      "naturephoto9.jpg",
    ],
  },
  {
    id: 8,
    title: "Pet Photography",
    image: "/art/petphoto1.jpg",
    category: ["photography", "all"],
    url: "/pet_photography",
    imageFolder: "art/Pet_Photography",
    images: [
      "petphoto1.jpg",
      "petphoto2.jpg",
      "petphoto3.jpg",
      "petphoto4.jpg",
      "petphoto5.jpg",
    ],
  },
  {
    id: 9,
    title: "Misc. Paintings",
    image: "/art/miscpainting1.jpg",
    category: ["paintings", "all"],
    url: "/misc_paintings",
    imageFolder: "art/Misc_Paintings",
    images: [
      "miscpainting1.jpg",
      "miscpainting2.jpg",
      "miscpainting3.jpg",
      "miscpainting4.jpg",
      "miscpainting5.jpg",
    ],
  },
  {
    id: 10,
    title: " Misc. Mixed Media",
    image: "/art/miscmixed1.jpg",
    category: ["mixed", "all"],
    url: "/mixed",
    imageFolder: "/art/Misc_Mixed_Media",
    images: ["mixed1.jpg", "mixed2.jpg", "mixed3.jpg", "mixed4.jpg"],
  },
  {
    id: 11,
    title: "Plaster Sculptures",
    image: "/art/plastersculpture1.jpg",
    category: ["sculptures", "all"],
    url: "/plaster_sculptures",
    imageFolder: "art/Plaster_Sculptures",
    images: [
      "plaster1.jpg",
      "plaster2.jpg",
      "plaster3.jpg",
      "plaster4.jpg",
      "plaster5.jpg",
      "plaster6.jpg",
    ],
  },
  {
    id: 12,
    title: "Portrait Photography",
    image: "/art/portraitphoto1.jpg",
    category: ["photography", "all"],
    url: "/portrait_photography",
    imageFolder: "art/Portrait_Photography",
    images: [
      "portraitphoto1.jpg",
      "portraitphoto2.jpg",
      "portraitphoto3.jpg",
      "portraitphoto4.jpg",
      "portraitphoto5.jpg",
      "portraitphoto6.jpg",
      "portraitphoto7.jpg",
      "portraitphoto8.jpg",
      "portraitphoto9.jpg",
      "portraitphoto10.jpg",
    ],
  },
  {
    id: 13,
    title: "Misc. Drawings",
    image: "/art/miscdrawing1.jpg",
    category: ["drawings", "all"],
    url: "/misc_drawings",
    imageFolder: "art/Misc_Drawings",
    images: [
      "miscdrawing1.jpg",
      "miscdrawing2.jpg",
      "miscdrawing3.jpg",
      "miscdrawing4.jpg",
    ],
  },
];

export default works;
